### ISSUE TITLE
'NoneType' object has no attribute 'data_dir'

### ISSUE THREAD

**Issue by natea** [edx/demo-test-course#6]
when i try to import the tarball, i get this error message:

"There was an error while importing the new course to our database. 'NoneType' object has no attribute 'data_dir'

**Comment by benpatterson** [comment]
@arbabnazar I don't suppose you've seen this situation? ^

**Comment by mattdrayer** [comment]
@natea @benpatterson -- I recall running into a situation like this several months ago -- I believe the issue is due to an XBlock type being specified in the course data but the reference is missing in github.txt

**Comment by natea** [comment]
is there any way of tracking down which XBlock it is? I presume the CMS
logs might be a good place to start?

On Fri, Dec 4, 2015 at 1:56 PM, Matt Drayer <notifications@github.com>
wrote:

> @natea <https://github.com/natea> @benpatterson
> <https://github.com/benpatterson> -- I recall running into a situation
> like this several months ago -- I believe the issue is due to an XBlock
> type being specified in the course data but the reference is missing in
> github.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edx/demo-test-course/issues/6#issuecomment-162051726>.
>



-- 


Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by mattdrayer** [comment]
I would compare the github.txt file for your installation against the one in master -- that's probably the fastest route

**Comment by mattdrayer** [comment]
IIRC it was really hard to work the reference down through the code and not much was present in the logs -- but we figured it out pretty quickly by diffing github.txt

**Comment by natea** [comment]
gotcha. we'll try that first.

On Fri, Dec 4, 2015 at 2:01 PM, Matt Drayer <notifications@github.com>
wrote:

> IIRC it was really hard to work the reference down through the code and
> not much was present in the logs -- but we figured it out pretty quickly by
> diffing github.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edx/demo-test-course/issues/6#issuecomment-162053186>.
>



-- 


Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by cptvitamin** [comment]
@natea I presume this was an issue with your local configuration?  Is there anything we can do to this course to prevent or solve this issue?  I have not been able to replicate it in my devstack, sandbox or edge.

**Comment by natea** [comment]
It's working now so you can close out this issue.

On Friday, March 4, 2016, Mark Sadecki <notifications@github.com> wrote:

> @natea <https://github.com/natea> I presume this was an issue with your
> local configuration? Is there anything we can do to this course to prevent
> or solve this issue? I have not been able to replicate it in my devstack,
> sandbox or edge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edx/demo-test-course/issues/6#issuecomment-192338603>.
>


-- 


Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331
